export default {
    jwtSecret: '@QEGTUI',
    userTable: 'tnv_beetsoft_user',
    pageItem: 10,
    exitCode: {
        success: 0,
        contentIsEmpty: 1,
        invalidParams: 2,
        invalidSignature: 3,
        outdatedSignature: 4,
        invalidService: 5,
        paramsIsEmpty: 6,
        duplicatePrimaryKey: 7,
        notFound: 8,
        notChange: 9,
        notUnique: 10,
        failed: 11,
    },
    exitCodeKey: 'exitCode',
    desKey: 'desc',
    inputDataKey: 'inputData',
}
