export default {
    jwtSecret: '@QEGTUI',
    userTable: 'tnv_beetsoft_user',
    categoryTable: 'tnv_category',
    pageItem: 10,
    exitCode: {
        success: 0,
        contentIsEmpty: 1,
        invalidParams: 2,
        invalidSignature: 3,
        outdatedSignature: 4,
        invalidService: 5,
        paramsIsEmpty: 6,
        duplicatePrimaryKey: 7,
        notFound: 8,
        notChange: 9,
        notUnique: 10,
        failed: 11,
    },
    message: {
        invalidSignature: 'Sai chu ky xac thuc',
        success: 'Ghi nhan thanh cong',
        failed: 'Ghi nhan that bai',
        invalidParams: 'Sai hoac thieu tham so',
        duplicate: 'Duplicate value',
        notFound: 'Khong ton tai ban ghi tuong ung',
        fieldNotFound: 'khong ton tai',
        notChange: 'Update that bai, data khong thay doi',
        notUnique: 'da ton tai, hay thu lai',
    },
    exitCodeKey: 'exitCode',
    desKey: 'desc',
    inputDataKey: 'inputData',
}
